import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:provider/provider.dart';
import '../../../shared/utils/format_utils.dart';
import '../../../shared/widgets/empty_state.dart';
import '../../../shared/widgets/shimmer_loading.dart';
import '../models/shopping_list.dart';
import '../providers/shopping_list_provider.dart';
import 'widgets/auto_generate_dialog.dart';
import 'widgets/shopping_item_tile.dart';

class ShoppingListScreen extends StatefulWidget {
  const ShoppingListScreen({super.key});

  @override
  State<ShoppingListScreen> createState() => _ShoppingListScreenState();
}

class _ShoppingListScreenState extends State<ShoppingListScreen> {
  String? _expandedListId;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<ShoppingListProvider>().loadShoppingLists();
    });
  }

  void _showAutoGenerate() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
      ),
      builder: (ctx) => const AutoGenerateDialog(),
    );
  }

  void _confirmDelete(String id) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Delete Shopping List'),
        content: const Text('Are you sure you want to delete this shopping list?'),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel'),
          ),
          TextButton(
            onPressed: () {
              Navigator.pop(ctx);
              context.read<ShoppingListProvider>().deleteShoppingList(id);
            },
            style: TextButton.styleFrom(foregroundColor: Colors.red),
            child: const Text('Delete'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Shopping'),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _showAutoGenerate,
        child: const Icon(Icons.auto_awesome),
      ),
      body: Consumer<ShoppingListProvider>(
        builder: (context, provider, _) {
          if (provider.isLoading && provider.shoppingLists.isEmpty) {
            return const ShimmerLoading(
              itemCount: 4,
              type: ShimmerType.list,
            );
          }

          if (provider.shoppingLists.isEmpty) {
            return EmptyState(
              icon: Icons.shopping_cart_outlined,
              title: 'No shopping lists yet',
              subtitle: 'Auto-generate from your recipes!',
              actionLabel: 'Auto Generate',
              onAction: _showAutoGenerate,
            );
          }

          return RefreshIndicator(
            onRefresh: () => provider.loadShoppingLists(),
            child: ListView.builder(
              padding: const EdgeInsets.all(16),
              itemCount: provider.shoppingLists.length,
              itemBuilder: (context, index) {
                final shoppingList = provider.shoppingLists[index];
                final isExpanded = _expandedListId == shoppingList.id;

                return _buildListCard(
                  context,
                  shoppingList,
                  isExpanded,
                  provider,
                )
                    .animate()
                    .fadeIn(
                      delay: Duration(milliseconds: 60 * index),
                      duration: 300.ms,
                    )
                    .slideY(begin: 0.05);
              },
            ),
          );
        },
      ),
    );
  }

  Widget _buildListCard(
    BuildContext context,
    ShoppingList shoppingList,
    bool isExpanded,
    ShoppingListProvider provider,
  ) {
    final theme = Theme.of(context);

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: Column(
        children: [
          // Header
          InkWell(
            onTap: () {
              setState(() {
                _expandedListId =
                    isExpanded ? null : shoppingList.id;
              });
            },
            borderRadius: BorderRadius.circular(20),
            child: Padding(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: Text(
                          shoppingList.name,
                          style: theme.textTheme.titleMedium?.copyWith(
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                      PopupMenuButton<String>(
                        onSelected: (value) {
                          if (value == 'delete') {
                            _confirmDelete(shoppingList.id);
                          }
                        },
                        itemBuilder: (ctx) => [
                          const PopupMenuItem(
                            value: 'delete',
                            child: Row(
                              children: [
                                Icon(Icons.delete_outlined,
                                    size: 20, color: Colors.red),
                                SizedBox(width: 8),
                                Text('Delete',
                                    style: TextStyle(color: Colors.red)),
                              ],
                            ),
                          ),
                        ],
                        icon: Icon(
                          Icons.more_vert,
                          color: theme.colorScheme.onSurfaceVariant,
                          size: 20,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 4),
                  Text(
                    FormatUtils.formatDate(shoppingList.date),
                    style: theme.textTheme.bodySmall?.copyWith(
                      color: theme.colorScheme.onSurfaceVariant,
                    ),
                  ),
                  const SizedBox(height: 12),
                  // Progress bar
                  Row(
                    children: [
                      Expanded(
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(4),
                          child: LinearProgressIndicator(
                            value: shoppingList.progress,
                            backgroundColor:
                                theme.colorScheme.outline.withOpacity(0.1),
                            valueColor: AlwaysStoppedAnimation<Color>(
                              shoppingList.progress >= 1.0
                                  ? theme.colorScheme.secondary
                                  : theme.colorScheme.primary,
                            ),
                            minHeight: 6,
                          ),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Text(
                        '${shoppingList.checkedItems}/${shoppingList.totalItems}',
                        style: theme.textTheme.bodySmall?.copyWith(
                          fontWeight: FontWeight.w600,
                          color: shoppingList.progress >= 1.0
                              ? theme.colorScheme.secondary
                              : theme.colorScheme.primary,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 4),
                  Row(
                    children: [
                      const Spacer(),
                      Icon(
                        isExpanded
                            ? Icons.expand_less
                            : Icons.expand_more,
                        size: 20,
                        color: theme.colorScheme.onSurfaceVariant,
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),

          // Item list (expanded)
          if (isExpanded) ...[
            Divider(
              height: 1,
              color: theme.colorScheme.outline.withOpacity(0.2),
            ),
            Padding(
              padding: const EdgeInsets.all(12),
              child: Column(
                children: shoppingList.items.asMap().entries.map((entry) {
                  final itemIndex = entry.key;
                  final item = entry.value;
                  return ShoppingItemTile(
                    item: item,
                    onToggle: () {
                      provider.toggleItemCheck(
                        shoppingList.id,
                        itemIndex,
                      );
                    },
                  )
                      .animate()
                      .fadeIn(
                        delay: Duration(milliseconds: 30 * itemIndex),
                        duration: 200.ms,
                      )
                      .slideX(begin: 0.03);
                }).toList(),
              ),
            ),
          ],
        ],
      ),
    );
  }
}
