import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../recipes/models/recipe.dart';
import '../../../recipes/providers/recipe_provider.dart';
import '../../providers/shopping_list_provider.dart';

class AutoGenerateDialog extends StatefulWidget {
  const AutoGenerateDialog({super.key});

  @override
  State<AutoGenerateDialog> createState() => _AutoGenerateDialogState();
}

class _AutoGenerateDialogState extends State<AutoGenerateDialog> {
  final _nameController = TextEditingController(text: 'Shopping List');
  final Set<String> _selectedRecipeIds = {};

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final provider = context.read<RecipeProvider>();
      if (provider.recipes.isEmpty) {
        provider.loadRecipes();
      }
    });
  }

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  Future<void> _generate() async {
    if (_selectedRecipeIds.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select at least one recipe.')),
      );
      return;
    }

    final name = _nameController.text.trim();
    if (name.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a list name.')),
      );
      return;
    }

    final shoppingProvider = context.read<ShoppingListProvider>();
    final result = await shoppingProvider.generateFromRecipes(
      name: name,
      recipeIds: _selectedRecipeIds.toList(),
    );

    if (result != null && mounted) {
      Navigator.pop(context, result);
    } else if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content:
              Text(shoppingProvider.errorMessage ?? 'Failed to generate list.'),
        ),
      );
      shoppingProvider.clearError();
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Padding(
      padding: EdgeInsets.only(
        left: 24,
        right: 24,
        top: 24,
        bottom: MediaQuery.of(context).viewInsets.bottom + 24,
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Auto-Generate Shopping List',
            style: theme.textTheme.titleLarge?.copyWith(
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            'Select recipes and ingredients will be automatically combined.',
            style: theme.textTheme.bodyMedium?.copyWith(
              color: theme.colorScheme.onSurfaceVariant,
            ),
          ),
          const SizedBox(height: 20),

          // List name
          TextField(
            controller: _nameController,
            decoration: InputDecoration(
              labelText: 'List Name',
              hintText: "This Week's Groceries",
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(20),
              ),
            ),
          ),
          const SizedBox(height: 16),

          // Recipe selection
          Text(
            'Select Recipes',
            style: theme.textTheme.bodyMedium?.copyWith(
              fontWeight: FontWeight.w600,
            ),
          ),
          const SizedBox(height: 8),
          Consumer<RecipeProvider>(
            builder: (context, recipeProvider, _) {
              if (recipeProvider.isLoading) {
                return const Center(
                  child: Padding(
                    padding: EdgeInsets.all(24),
                    child: CircularProgressIndicator(strokeWidth: 2),
                  ),
                );
              }

              if (recipeProvider.recipes.isEmpty) {
                return Padding(
                  padding: const EdgeInsets.all(24),
                  child: Center(
                    child: Text(
                      'No recipes available.',
                      style: theme.textTheme.bodyMedium?.copyWith(
                        color: theme.colorScheme.onSurfaceVariant,
                      ),
                    ),
                  ),
                );
              }

              return ConstrainedBox(
                constraints: const BoxConstraints(maxHeight: 250),
                child: ListView.builder(
                  shrinkWrap: true,
                  itemCount: recipeProvider.recipes.length,
                  itemBuilder: (context, index) {
                    final recipe = recipeProvider.recipes[index];
                    final isSelected =
                        _selectedRecipeIds.contains(recipe.id);

                    return CheckboxListTile(
                      value: isSelected,
                      onChanged: (checked) {
                        setState(() {
                          if (checked == true) {
                            _selectedRecipeIds.add(recipe.id);
                          } else {
                            _selectedRecipeIds.remove(recipe.id);
                          }
                        });
                      },
                      title: Text(
                        recipe.title,
                        style: theme.textTheme.bodyMedium?.copyWith(
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                      subtitle: Text(
                        '${recipe.category} | ${recipe.servings} servings',
                        style: theme.textTheme.bodySmall?.copyWith(
                          color: theme.colorScheme.onSurfaceVariant,
                        ),
                      ),
                      activeColor: theme.colorScheme.primary,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(12),
                      ),
                      contentPadding: EdgeInsets.zero,
                    );
                  },
                ),
              );
            },
          ),
          const SizedBox(height: 16),

          // Selected recipe count
          if (_selectedRecipeIds.isNotEmpty)
            Text(
              '${_selectedRecipeIds.length} recipes selected',
              style: theme.textTheme.bodySmall?.copyWith(
                color: theme.colorScheme.primary,
                fontWeight: FontWeight.w600,
              ),
            ),
          const SizedBox(height: 16),

          // Generate button
          Consumer<ShoppingListProvider>(
            builder: (context, shoppingProvider, _) {
              return FilledButton(
                onPressed: shoppingProvider.isGenerating ? null : _generate,
                child: shoppingProvider.isGenerating
                    ? const SizedBox(
                        width: 24,
                        height: 24,
                        child: CircularProgressIndicator(
                          strokeWidth: 2,
                          color: Colors.white,
                        ),
                      )
                    : const Text('Generate List'),
              );
            },
          ),
        ],
      ),
    );
  }
}
